# Generated by Django 5.1 on 2024-08-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Name of User')),
                ('email', models.EmailField(default='example@email.com', max_length=100, unique=True, verbose_name='Email adress')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Last Name')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Phone Number')),
                ('image', models.ImageField(default='default.jpg', max_length=200, upload_to='profile/', verbose_name='Profile Picture')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
