version: '3.3'  

services:
  db_posgres:
    image: postgres:latest
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dent
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: develop
    restart: always
  web:
    image: dentbyte
    container_name: dentbyte
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app
    links:
      - db_posgres
    depends_on:
      - db_posgres
volumes:
  postgres_data:
