version: '3.7'  

services:
  web:
    image: dentbyte
    container_name: dentbyte
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - db_posgres
    depends_on:
      - db_posgres
    command: ["sh", "./start.sh"]
    extra_hosts: 
      - "host.docker.internal:host-gateway"
  db_posgres:
    image: postgres:latest
    ports: 
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: dent
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: develop
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db_posgres
    restart: always
    extra_hosts: 
      - "host.docker.internal:host-gateway"
volumes:
  postgres_data:
