version: '3.3'  

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
  web:
    image: dentbyte
    container_name: dentbyte
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
volumes:
  postgres_data: