# Generated by Django 5.1 on 2024-09-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='age',
            field=models.IntegerField(default=10),
        ),
    ]
